default: &default
  adapter: mysql
  database: <%= ENV['DATABASE_NAME'] || 'espnsports' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'root' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || '3306' %>

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default


# Database for scrapers
# So we can use ActiveRecord::Base.estabilish_connection
statistics:
  <<: *default
  database: Statistics