default: &default
  adapter: mysql2
  database: <%= ENV['DATABASE_NAME'] || 'espnsports' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'root' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || '3306' %>
  reconnect: true

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
